baseURL = "/"
languageCode = "en-us"
title = "My Go Project Docs"
theme = "book"

# Optional: enable some nice Hugo Book features
[params]
  BookToC = true
  BookSearch = true
  BookSection = "docs"  # where your docs live

[markup]
  [markup.highlight]
    noClasses = false
