baseURL = "/"
languageCode = "en-us"
title = "My Go Project Docs"
theme = "book"

# JSON output for search (Book supports this)
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  BookToC = true
  BookSearch = true
  BookSection = "docs"

[markup]
  [markup.highlight]
    noClasses = false
