baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Go HTTP Server Documentation'

theme = 'book'

[params]
  BookTheme = 'auto'
  BookMenuBundle = '/menu'
  BookSection = 'docs'
  BookRepo = 'https://github.com/username/go-http-server'
  BookEditPage = true
  BookSearch = true
  BookComments = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[menu]
  [[menu.before]]
    name = "Documentation"
    url = "/docs/"
    weight = 10

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']
